# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Runnable Use Cases
email: support@runnable.com
description: Articles that explain how Runnable can be used to solve problems for development teams.
url: https://runnable.com # the base hostname & protocol for your site

seo:
  type: TechArticle

# Build settings
markdown: kramdown

gems:
  - jekyll-seo-tag
  - jekyll-sitemap

permalink: /:categories/:title

sass:
  sass_dir: _sass/
